name: 'rocrate-to-html'
description: 'This takes the rocrate json and preview.html files and publishes them on github pages'
branding:
  icon: 'upload-cloud'
  color: 'red'
inputs:
  crate_path:  
    description: 'Path to rocrate files'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate_path }}