name: 'rocrate-to-html'
description: 'This takes the rocrate json and preview.html files and publishes them on github pages'
branding:
  icon: 'upload-cloud'
  color: 'red'
inputs:
  crate_path:  
    description: 'URL to the ro-crate'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate_path }}